### ISSUE TITLE
Deezer does not support the current implementation anymore

### ISSUE THREAD

**Issue by MTindev** [imanel/deezplayer#24]
Hello,

When opening the app (version 2.0.1), a message is displayed, over the Deezer website.
It's English translation is : "Do not run after the time lost, Deezer is no longer used with this version of your browser. Update your browser or download our computer app to continue enjoying your music.".

**Comment by imanel** [comment]
Since Deezer is now providing [official app](https://www.deezer.com/en/download/) that is using exactly the same technology there's really no reason to support this application anymore. Is there any reason why you prefer DeezPlayer over official app?

**Comment by MTindev** [comment]
Because the current official app has been built for Windows and MacOS only, and not for *Linux* (Ubuntu, etc).
But I understand the stake is low, from now on.
In any case, thank you for the good job you have done until now !

**Comment by imanel** [comment]
I was not aware of that - this means that there is solid reason for supporting DeezPlayer in future. Just released [v2.0.2](https://github.com/imanel/deezplayer/releases/tag/v2.0.2) that should fix it, let me know if it fixed issue for you. Happy using!

**Comment by MTindev** [comment]
Thanks for the release. It works like a charm :+1:.
