### ISSUE TITLE
Controllers of Player not Working

### ISSUE THREAD

**Issue by joaoeudes7** [imanel/deezplayer#25]
This code is not working in Arch Linux, because media controls do not respond
Note: I used debtap to convert to Arch package
 
```
  globalShortcut.register 'MediaPlayPause',     -> runJS "dzPlayer.control.togglePause();"
  globalShortcut.register 'MediaStop',          -> runJS "dzPlayer.control.pause();"
  globalShortcut.register 'MediaNextTrack',     -> runJS "dzPlayer.control.nextSong();"
  globalShortcut.register 'MediaPreviousTrack', -> runJS "dzPlayer.control.prevSong();"
```

**Comment by imanel** [comment]
This is [well known](https://github.com/electron/electron/issues/5268) problem with Arch Linux (it works with other distributions). Unfortunately there's nothing I can do about it - it's on system level, and messing with dbus directly sounds like a horrible idea.
